### ISSUE TITLE
Workaround Qt losing connectivity

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/libqmatrixclient#109]
On poorer networks (cellular, some WiFi), QNAM tends to lose connectivity and not recover back - even if the network is actually there. Apparently, libqmatrixclient has to step in and somehow recover (recreate QNAM? reset its state?) instead.

**Comment by Quiark** [comment]
I did
```
    static QNetworkAccessManager* _nam = new QNetworkAccessManager();
    QObject::connect(_nam ,&QNetworkAccessManager::networkAccessibleChanged, [] (QNetworkAccessManager::NetworkAccessibility accessible) {
        _nam->setNetworkAccessible(QNetworkAccessManager::Accessible);
    });
```

and it seems to help. I'm also hypothesizing that simply calling `setNetworkAccessible` once on start will tell Qt to stop guessing and not change it.

**Comment by KitsuneRal** [comment]
@Quiark, thanks. That doesn't look quite fair but given that the library simple fires retries without looking into actual connectivity, this might be a good enough way out for the time being.

**Comment by KitsuneRal** [comment]
The mentioned workaround didn't even work for one of those crappy networks that I met; the problem lies somewhere in the depths of `QNativeWifiEngine` from `plugins/bearer` that apparently cannot gather a reasonable configuration from what (at least) Windows 7 is able to give it. Since we're not really manipulating network interfaces, I consider tearing the whole bearer management part entirely off. Case in point: with no changes to the source code (even without the workaround above), deleting `bearer/` directory of a dedicated Qt installation allows Quaternion to smoothly run with no troubles.

**Comment by KitsuneRal** [comment]
To be on the safe side, I'm passing `-DQT_NO_BEARERMANAGEMENT` in `CMAKE_CXX_FLAGS` in Quaternion, not in libqmatrixclient. Other clients may want to do the same.

**Comment by KitsuneRal** [comment]
Even `-DQT_NO_BEARER_MANAGEMENT` wasn't enough to tell Qt not to load those plugins ;(

**Comment by KitsuneRal** [comment]
Ok, the above failure was with `setNetworkAccessible()` called once upon creation of QNAM. However, if I do it upon every `networkAccessibleChanged()`, exactly as @Quiark proposed above, the workaround actually works. I'd be much happier with tearing off the whole bearer management thing but Qt doesn't allow to do that - if it finds a plugin at runtime, it loads it and I couldn't find a way to disable specific plugins from loading. So apparently the described workaround is to be in libqmatrixclient until Qt becomes better at bearer management.
