### ISSUE TITLE
cmake no 'install' target

### ISSUE THREAD

**Issue by alexandergraul** [QMatrixClient/libqmatrixclient#113]
Hi,
I tried to build and package this as a shared library for openSUSE.
`cmake install` failed with `make install -C build has no target 'install'`

**Comment by KitsuneRal** [comment]
True; as mentioned in README.md, the library haven't really been in use standalone, usually people build/package the client application with the library bundled. Something to address for the next release.

**Comment by KitsuneRal** [comment]
@alexandergraul any updates on that? I'm going for 0.2 release of the library this week.

**Comment by KitsuneRal** [comment]
Strictly speaking, this does not completely address the original issue, which was packaging a _shared_ library. #195 is created to track the work on the shared library.
