### ISSUE TITLE
Provide an option to build a shared library

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/libqmatrixclient#195]
This is a continuation of the work started in #113 to allow separate packaging of the library and clients using it.

**Comment by KitsuneRal** [comment]
@alexandergraul, you're more than welcome to continue your packaging effort on this new base.

**Comment by alexandergraul** [comment]
@KitsuneRal thank you for finishing the cmake install part, I have built a first version of an rpm providing the shared library. I now need to polish it and build Quaternion against it, I will report back once I've done that.

**Comment by KitsuneRal** [comment]
@alexandergraul, thanks! Did you need to update the library code to make the RPM? If yes, can you please make a PR to this repo with the words "Closes #195"? This is just to track the current state of affairs, you can follow up with more changes further on.

**Comment by alexandergraul** [comment]
I added a patch to remove some cmake install targets, I guessed that qmc-example and the android ndk module are not needed. Is that correct or do you want them installed? I'll update the rpm / make a PR putting them in conditionals once I know which way to go.

You can have a look at my current rpm here: https://build.opensuse.org/package/show/home:agraul/libqmatrixclient. I plan to submit it to a devel project later on so it can end up in openSUSE one day. Also gonna look into differences of Fedora spec files and see if I get a working version for it.

**Comment by KitsuneRal** [comment]
Thanks for a quick return!
It's better to keep `qmc-example` around so that there were a way to check the library's sanity. That, of course, implies that `qmc-example` should be dynamically linked with it. If it's not dynamically linked then it's better to keep it out.
As for the Android NDK file, whether or not to package it (and how) depends completely on the policy of the specific distribution. Formally it belongs to the -devel package. I don't have hard feelings towards that, I just noticed an option to generate it while digging through CMake documentation and thought that I could use it. It would be proper to wrap its installation in a conditional.

**Comment by KitsuneRal** [comment]
...and, judging by the build log, CMake does the right thing and `qmc-example` is dynamically linked. Then I think it should be installed (you might actually want to take a look at other library packages that have some executable artifacts - puzzlingly, `gdk-pixbuf` comes to my mind for an example.
Overall, since it's only a question of specific packaging, I think I can close this issue. See you further in https://github.com/QMatrixClient/Quaternion/issues/239, this time with the working Quaternion package :)
