### ISSUE TITLE
Crashes with "too large document"

### ISSUE THREAD

**Issue by Powersource** [QMatrixClient/libqmatrixclient#216]
### Description

Quaternion crashes with:
```
% quaternion --debug
Debug:  true
Using QQuickView wrapper instead of QQuickWidget
qml: QML view loaded
qml: Base colours: #000000 on #ffffff
--- Show time!
libqmatrixclient.jobs.sync: "SyncJob-1" status 106: too large document
zsh: segmentation fault (core dumped)  quaternion --debug
```
or another time with:
```
% quaternion 
Debug:  false
Using QQuickView wrapper instead of QQuickWidget
qml: QML view loaded
qml: Base colours: #000000 on #ffffff
--- Show time!
libqmatrixclient.jobs.sync: SyncJob-1|https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000
libqmatrixclient.jobs.sync:    504 Gateway Time-out (tentative)
libqmatrixclient.jobs.sync: "SyncJob-1" status 100: Unknown error
libqmatrixclient.jobs.sync: SyncJob-1|https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000
libqmatrixclient.jobs.sync:    504 Gateway Time-out (final)
libqmatrixclient.jobs.sync: "SyncJob-1" status 100: Error transferring https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000 - server replied: Gateway Time-out
libqmatrixclient.jobs.sync: "SyncJob-1": retry #1 in 5 s
libqmatrixclient.jobs.sync: SyncJob-1|https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000
libqmatrixclient.jobs.sync:    504 Gateway Time-out (tentative)
libqmatrixclient.jobs.sync: "SyncJob-1" status 100: Unknown error
libqmatrixclient.jobs.sync: SyncJob-1|https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000
libqmatrixclient.jobs.sync:    504 Gateway Time-out (final)
libqmatrixclient.jobs.sync: "SyncJob-1" status 100: Error transferring https://matrix.org/_matrix/client/r0/sync?filter=%7B%22room%22: %7B %22timeline%22: %7B %22limit%22: 100 %7D %7D %7D&timeout=30000 - server replied: Gateway Time-out
libqmatrixclient.jobs.sync: "SyncJob-1": retry #2 in 10 s
libqmatrixclient.jobs.sync: "SyncJob-1" status 106: too large document
zsh: segmentation fault (core dumped)  quaternion
```
Please tell me if I should open this issue in Quaternion's repo instead.

Some information I think might be relevant: I installed Fractal a month or so ago and it used way more ram than was usual. The developers of it were confused (I'm not connected to a too high amount of channels or anything) but I don't think we opened an issue. I also have major performance problems with Riot (which is why I wanted to try Quaternion) but I think other people may have similar issues there, not sure really. Anyway, I think the issue could be that my account somehow is attached to some channel/file that's automatically getting downloaded in all these clients, bogging them down/breaking them. Anything I can do to investigate further?

### Steps to reproduce

- Launch Quaternion
- Log in as me (I guess?), not necessarily for the first time.
- Wait for it to sync for a bit.
- Get a popup saying that the sync failed.
- Click anything, crash.

### Version information

- Quaternion: 0.0.9.2
- libqmatrixclient: 0.3.0.2
- qt5-base: 5.11.1-1
- Installed with https://aur.archlinux.org/packages/quaternion/
- Arch linux. `Linux pc 4.17.3-1-ARCH #1 SMP PREEMPT Tue Jun 26 04:42:36 UTC 2018 x86_64 GNU/Linux`

**Comment by KitsuneRal** [comment]
It's a problem in Quaternion but it's libqmatrixclient does not have safe defaults for that. This issue is enough, you don't need to do anything, the fix for the library is in df164cd856a34d8c1462793a40e56d387389b82f (i.e., please update to the most recent master).
Unfortunately, it's only a fix for the crash, not for the "too large document" error, the cause of which is Qt being unable to deal with too large JSON documents. Fixing this has lower priority, as works are now under way to drastically reduce the size of those documents coming from the server in the first place: https://github.com/matrix-org/synapse/pull/2970
