### ISSUE TITLE
A recent commit uses QtPrivate from Qt-5.7+ (your official minimum Qt is 5.4)

### ISSUE THREAD

**Issue by Kaffeine** [QMatrixClient/libqmatrixclient#284]
Commit https://github.com/QMatrixClient/libqmatrixclient/commit/ac5daf2ed495a932aba23606f5b3d0dca5aaf676 uses QtPrivate template that only available (what a word for a *private* API) since Qt-5.7 https://github.com/qt/qtbase/commit/88d7c8f963414f4d3ac7a406faddcc074ca6462d. Please either change the code (we still have only 5.6 on Sailfish OS) or bump the minimal Qt version in CMakeLists.

I think that a compromise solution would be to copy the private code to your codebase. It is only 12 lines of code after all.

**Comment by Kaffeine** [comment]
I think I can make a PR if you'll agree on the proposed solution.

**Comment by KitsuneRal** [comment]
Well, to be accurate (and just to clarify the overall situation), the library officially supports Qt 5.6; Qt 5.4 in CMakeLists.txt is just a way to allow compilation against older frameworks (such as Ubuntu Touch) but the burden of keeping buildability for those is on client authors.

With that said - the observation is valid, I confused the Quaternion codebase (which officially depends on Qt 5.7) with libQMatrixClient.

**Comment by KitsuneRal** [comment]
@Kaffeine a PR is welcome but please make it so it only kicks in for versions below Qt 5.7. I know it's private API but I really don't want to copy-paste something available (and extremely unlikely to disappear) in upstream libs.
