### ISSUE TITLE
Release Version 0.5

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/libqmatrixclient#291]
Pre-check:
- [x] There are no pending issues in the Roadmap for this release (if there are, move them away or close them)
- [x] Check the latest branch/commit:
  - [x] in the repo
  - [x] Travis CI: [![libQMatrixClient@Travis](https://img.shields.io/travis/QMatrixClient/libqmatrixclient/master.svg)](https://travis-ci.org/QMatrixClient/libqmatrixclient/branches);
  - [x] AppVeyor CI: [![libQMatrixClient@AppVeyor](https://img.shields.io/appveyor/ci/QMatrixClient/libQMatrixClient/master.svg?logo=appveyor)](https://ci.appveyor.com/project/libQMatrixClient/quaternion).

Actions:
- [x] Check the version number in `CMakeLists.txt`
- [x] Rebuild (from scratch) qmc-example and run it locally
- [x] Check that contents of README.md and CONTRIBUTING.md are up-to-date
- [x] Go to the [Releases page](https://github.com/QMatrixClient/libQMatrixClient/releases) and make a draft for release notes:
  - [x] Thank all contributors whose commits landed in this release
  - [x] Describe all notable fixes/enhancements/API breakage
- [x] `git commit && git push`
- [x] Finalise the release at GitHub:
  - [x] Fill in the tag
  - [x] Publish release notes
- [x] Update the topic in #quaternion

Post-check:
- [x] Open the release page in Incognito/Privacy mode; check:
  - [x] the version (should be "Version ###");
  - [x] the Git tag (should be "N.M.L", NOT "N.M");

- [x] Congratulate everyone and have a drink :)

**Comment by jubalh** [comment]
@KitsuneRal nice! Quick question: should Quaternion 0.0.9.3 build with this?

**Comment by KitsuneRal** [comment]
No, Quaternion 0.0.9.3 will not build with this because API has been broken in a few places. It's not too difficult to port it to lib 0.5 but I highly recommend using Quaternion 0.0.9.4 beta that I will publish later today.
