### ISSUE TITLE
Crash in imageprovider.cpp

### ISSUE THREAD

**Issue by vranki** [QMatrixClient/libqmatrixclient#293]
### Description

Got this crash when running Spectral built against master version of libqmatrixclient.

### Steps to reproduce

Not sure, this just happened. Stack trace:

1  QScopedPointer<QMatrixClient::BaseJob::Private, QScopedPointerDeleter<QMatrixClient::BaseJob::Private>>::operator->                                                            qscopedpointer.h   118 0x555555648dc2 
2  QMatrixClient::BaseJob::error                                                                                                                                                  basejob.cpp        588 0x55555564740c 
3  ThumbnailResponse::prepareResult                                                                                                                                               imageprovider.cpp  49  0x55555572f2f7 
4  QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ThumbnailResponse:: *)()>::call(void (ThumbnailResponse:: *)(), ThumbnailResponse *, void * *) qobjectdefs_impl.h 152 0x5555557300a4 
5  QtPrivate::FunctionPointer<void (ThumbnailResponse:: *)()>::call<QtPrivate::List<>, void>(void (ThumbnailResponse:: *)(), ThumbnailResponse *, void * *)                       qobjectdefs_impl.h 185 0x555555730027 
6  QtPrivate::QSlotObject<void (ThumbnailResponse:: *)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void * *, bool *)                          qobjectdefs_impl.h 414 0x55555572ff58 
7  QObject::event(QEvent *)                                                                                                                                                                              0x7ffff6397b42 
8  QApplicationPrivate::notify_helper(QObject *, QEvent *)                                                                                                                                               0x7ffff7413ebc 
9  QApplication::notify(QObject *, QEvent *)                                                                                                                                                             0x7ffff741b450 
10 QCoreApplication::notifyInternal2(QObject *, QEvent *)                                                                                                                                                0x7ffff63674c8 
11 QCoreApplicationPrivate::sendPostedEvents(QObject *, int, QThreadData *)                                                                                                                              0x7ffff636a027 
12 ??                                                                                                                                                                                                    0x7ffff63c4cd3 
13 g_main_context_dispatch                                                                                                                                                                               0x7ffff364c387 
14 ??                                                                                                                                                                                                    0x7ffff364c5c0 
15 g_main_context_iteration                                                                                                                                                                              0x7ffff364c64c 
16 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                            0x7ffff63c42ef 
17 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)                                                                                                                                               0x7ffff63657ea 
18 QCoreApplication::exec()                                                                                                                                                                              0x7ffff636e9a0 
19 main                                                                                                                                                                           main.cpp           81  0x5555557180e2 

My analysis: imageprovider.cpp:49 and later references variable "job", which is a null pointer in this situation. Check it for nullness?

### Version information

- **The client application**: Spectral
- **libqmatrixclient version if you know it**: master
- **Qt version**: 5.12
- **Install method**: flatpak
- **Platform**: Ubuntu 18.04

**Comment by vranki** [comment]
This seems to fix the crash, not sure if it's correct:

void ThumbnailResponse::prepareResult() {
  if(job) {
...

**Comment by KitsuneRal** [comment]
@vranki you may want to join `#qmatrixclient:matrix.org` - I discussed that problem, and the fix, in there a couple of hours ago.

**Comment by KitsuneRal** [comment]
In short, you may be interested in https://github.com/QMatrixClient/Quaternion/commit/4c0020385a3cf424796a23887879eda23eba5104

**Comment by KitsuneRal** [comment]
https://gitlab.com/b0/spectral/merge_requests/41
