### ISSUE TITLE
Detect join of already joined user as a data change

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/libqmatrixclient#41]

**Comment by KitsuneRal** [comment]
Judging by the code and by Quaternion behaviour, I suppose that it's exactly how things work: when an `m.room.member` "join" event comes about a user that's already joined, it's processed as a data change, and respective signals (`nameChanged` or `avatarChanged`) are emitted to reflect the change in clients. Is there anything else here I don't notice, or it's just a outdated issue that can be closed now?

**Comment by maralorn** [comment]
No, as far as I can tell this is not a an outdated issue. When I submitted it the event also was already correctly showing the data. I am merely talking about how to display it properly. It is very confusing, that the timeline shows a join.

**Comment by KitsuneRal** [comment]
Aah, you mean displaying - thanks for clarification. Right, it's still "joined" even on updates. I wonder if it relates to Quaternion rather than libqmatrixclient - the messages are formed on the Quaternion side.

**Comment by maralorn** [comment]
I thought it would make sense to use a different event for it. That's why I put it the issue here. But that's maybe not the way to go.

Am 23. September 2017 06:48:27 MESZ schrieb Kitsune Ral <notifications@github.com>:

**Comment by KitsuneRal** [comment]
Given that there's no difference between joining and updating on the wire, I don't think it's worth a different event. I'd rather modify `RoomMemberEvent` by adding some flag or so. Just a thought passing by.

**Comment by KitsuneRal** [comment]
#105 is fixed, in particular for member events, which means the library part of this issue is complete. Quaternion will reflect those changes once I pushed a respective commit to its repo.
