### ISSUE TITLE
user::avatar() has a memory leak

### ISSUE THREAD

**Issue by maralorn** [QMatrixClient/libqmatrixclient#45]
the user::avatar() method has this scaledAvatar cache list. And everytime we don’t have a scaledAvatar for the given size we generate a new one. Becauso auf KeepAspectRatio, the new avatar will not have the requested size, so we will calculate a new one everytime and the list gets longer and longer.

**Comment by maralorn** [comment]
I am working with avatars anyway, so I already have a fix for that.

**Comment by KitsuneRal** [comment]
Right, now that I looked again at the code, I realised that strict checking for size (on both coordinates) has a big risk to fail due to `KeepAspectRatio`. I suppose you're still preserving the aspect ratio and change the size checking instead?

**Comment by maralorn** [comment]
So actually my approach would be to just crop the picture to the requested size.
I have the code for that ready.

**Comment by KitsuneRal** [comment]
Fixed long ago.
