### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by bbernhard** [QMatrixClient/libqmatrixclient#70]
Hi,

first of all, many thanks for all the work that is put into this library. I am watching `libqmatrixclient` for a while and it is really great to see all this progress!

I am thinking about using the library in one of my iOs apps. But unfortunately it seems like the current license isn't really suitable for iOs, as the apple app store doesn't allow libraries to be dynamically linked. So I wanted to ask if there is any chance to change the license to something that can be better used together with iOs. Maybe MIT or Apache 2.0? 

Many thanks for your time!

Have a nice day,
Bernhard

**Comment by KitsuneRal** [comment]
FWIW, libqmatrixclient was only tried with static linkage until now, anyway. And LGPL is equally applicable to both ways of linkage. I don't quite understand the problem you're facing so far - could you please elaborate?

**Comment by KitsuneRal** [comment]
Oh, wait, sorry - LGPL does restrict licensing on static linkage, now that I re-read its terms. Ok, so you want to make a client under a non-GPL/LGPL license?

**Comment by bbernhard** [comment]
@KitsuneRal Thanks for your fast response!

I am not a expert regarding the license stuff, but as far as I know LPGL requires that a library is linked in a way, so that the user of the application can download it's own copy of the library, build it and link against the newly built library. Unfortunately Apple doesn't allow dynamic linking in iOs applications - all libraries need to be statically linked (the only exception I know is, when you link against iOs system libraries - you can link against those dynamically). See also: http://roadfiresoftware.com/2013/08/the-problem-with-using-lgpl-v2-1-code-in-an-ios-app/ (the article is already a few years old, but as far as I know Apple hasn't changed it's policies). 

I researched the topic a little bit further and there seem to be a few people who claim that LGPL stuff can be used in iOs apps (under certain precautions). It looks like that it's a legal greyzone. But for me personally it's too risky to do that (I don't want to get in any legal troubles because of that). So I think the only possibility to use the library would be if it's licensed in a way that one can use it in iOs apps. As far as I know Apache 2.0, MIT and BSD are licenses which are safe for iOs. 

I personally also totally understand if you want to stick with the LGPL. ;-) I am currently in the process of evaluating different chat protocols (Matrix, XMPP...) and different (open source) libraries. During that I came across the great libqmatrixclient library, which looks really promising. But before I go further with my testing and implementation I wanted to make sure that the license matches my needs :)

Thanks,
Bernhard

**Comment by KitsuneRal** [comment]
Bernhard, IANAL but the quoted part of LGPL explicitly states that is acceptable to distribute the source code of the "work that uses...". So unless you want to keep the source code with you, you should be fine. Hence my question above - do you plan to use libqmatrixclient in a closed-source software? (If not, I don't see a problem.) If yes, I wonder what you're going to do with Qt - use their commercial license?
Thanks for kind words about the library, by the way :)

**Comment by bbernhard** [comment]
Sorry, missed that part completely. ;) Yeah, I am currently using the Qt commercial version (Indie License) with closed sourcecode. I mainly choosed the commercial version because of the great Qt Quick Compiler. But as the Qt team is now working actively on bringing the full Qt Quick Compiler support also to the open source version I am really thinking of making my sourcecode publicly available and switching to the open source version. 

However, opensourcing the stuff probably takes some time to refactor the whole repo. (there are some API keys encrypted with git-crypt in there and IP addresses that I don't want to make publicly available - even when they are encrypted). And also some interfaces need some refactoring to cleanly separate sensible informations from business logic. So all in all it's for sure a few weeks of work. 

Unfortunately that's something I can't invest time right now, although I would really like to. So for now I think I LGPL is no option for me (at least for the iOs version). But I also totally understand your decision to use LGPL for that :)

Cheers,
Bernhard

**Comment by KitsuneRal** [comment]
Ok, I see. Well, as you probably know, I'll have to collect an agreement from all those who contributed the code, which is going to take some time. Personally, I don't see a problem to include an explicit allowance to statically link libqmatrixclient with closed-source code on iOS but let's see what @Fxrh thinks, as well as other contributors.

**Comment by bbernhard** [comment]
Thank you very much, I really appreciate your decision a lot!

Let's see what the others are thinking about that :)

Thanks again,
Bernhard

**Comment by KitsuneRal** [comment]
@davidar, @maralorn, @elvisangelaccio, @Quiark, feel free to weigh in.

**Comment by Quiark** [comment]
Hi, I don't mind changing it.

**Comment by elvisangelaccio** [comment]
See https://trac.ffmpeg.org/ticket/1229

IANAL either, but as far as I understand it is possible to comply with the LGPL even if you are using static linking. You need to provide the object files of your app so that people can re-link the LGPL lib (if they want).

There is the additional issue of Apple's signing key that people don't have and can't use to reproduce the derived work, but that's Apple's problem. It is Apple that distributes your app through the Apple store, not you. And the LGPL says "You are not responsible for enforcing compliance by third parties with
this License.".

**Comment by Fxrh** [comment]
For the possibility mentioned by @elvisangelaccio, see also https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic. Would that be an option?

While I would be OK with allowing static linking, I don't really like the idea of using a non-standard license. That's a thing for lawyers to write imho (and defending it would also be a lot harder). Is there a license that keeps the copyleft part but would be easier to use for the apple store?

**Comment by bbernhard** [comment]
First of all, thanks for your quick responses. It's always great to see open source projects that are as active and well maintained as this one. Thanks!

Many thanks for the links. I didn't know that one can statically link against LGPL'd libraries when providing the objects. It's not the ideal solution, but it's definitely ok for me to do that. So I think I can now start evaluating the Matrix protocol and `libqmatrixclient`. :)

Thanks again for your help, really appreciated! 

Cheers,
Bernhard

**Comment by KitsuneRal** [comment]
Thanks everybody!
