### ISSUE TITLE
Introduce automatic tests

### ISSUE THREAD

**Issue by KitsuneRal** [QMatrixClient/libqmatrixclient#73]
It's essential for a library to have tests, so let's get them already. Aside from the obvious QtTest option, a single-header [Catch](https://github.com/philsquared/Catch/) is in fashion these days, so I took time to dive in both. If anybody wants to throw something else, please do (preferably with pros and cons as below).

QtTest pros:
- supports GUI testing and QML (though it's not quite important for libqmatrixclient _as of yet_)
- native to Qt, no extra deps or repos; integrates into Qt Creator and KDevelop
- embedded cross-platform benchmarking appliance

QtTest cons:
- [xUnit](https://en.wikipedia.org/wiki/XUnit)-styled splitting of the test suite into functions makes the whole thing less flexible
- more keystrokes per test
- doesn't have embedded integration into CI (other than logging to console and returning non-zero from the testing-process)

Catch pros:
- allows considerably more concise and flexible test code thanks to SECTIONs
- integrates into CLion and in general is more integrable thanks to the JUnit reporter.
- though it's an external dependency, in fact it's an advantage in this particular case since the release cycle of Catch is shorter than that of QtTest, and the provided latest-version-fetching code for CMake in the documentation almost entirely removes inconvenience of having another git submodule

Catch cons:
- single-header is a biggie; even though Catch mitigates this by clever #ifdefs, it's still a biggie
- no embedded support for GUI testing and (maybe?) Qt-related concepts
  - this one is dubious for now, since libqmatrixclient is and will be intentionally GUI-less
  - note about Qt signals: detecting a signal in fact boils down to connect()ing a lambda to it, which is not a big deal
- no way to intercept failed assertions (because everything is executed in a single process)

**Comment by elvisangelaccio** [comment]
I've never used Catch. One advantage of the "splitting" of QtTest is that you can choose to not build tests if you don't need/want them. Is that possible with Catch?

**Comment by KitsuneRal** [comment]
@elvisangelaccio, there's nothing stopping you from writing tests in a separate file from the .cpp and build tests as a completely separate set of sources (using the same headers and lib, of course) - both in case of QtTest and of Catch. What I liked about Catch is that since it's top-level entity is a macro, it itself swallows an #ifdef that controls whether the test is build or not. So even if the test resides in the same cpp file (which can be absolutely awesome from the point of code locality - it's good to write a unit test next to the unit itself), you can still switch its building off entirely, as if it weren't there. Feeding the longer .cpp to the C++ preprocessor is inevitable, though - it's either code locality or shorter files, no matter QtTest or Catch.

**Comment by suy** [comment]
AFAIK, the features in QtTest to test GUIs, QSignalSpy, etc. don't require that you use the "runner" of QtTest. Only that you will need to link to QtTest, and also have the catch includes.

One reason to use QtTest in full, though, is that you get nicer output of values that use the Qt types when there is a mismatch. If you need to compare two QStringLists, does Catch give you a nice output without writing your own operator to standard streams?

**Comment by KitsuneRal** [comment]
Without writing my own operator - obviously it doesn't; but that's a one-time work with very good return-on-investment. Thanks for the idea about using Catch and QtTest in combination - it looks quite good, to run tests in Catch but use GUI-crawling and signal-tracking capabilities of QtTest.

**Comment by KitsuneRal** [comment]
As the first shot at this, a primitive run of qmc-example is done in Travis CI. The biggest problem for autotest frameworks (even QtTest) is, unsurprisingly, completely asynchronous operation of libqmatrixclient. So more extended and more "proper" test coverage is postponed; going without testing frameworks for now.

**Comment by KitsuneRal** [comment]
Those who are interested in looking at smoke-test messages coming from the Travis pipeline are welcome to `#qmc-test:matrix.org`. This one is closed now.
