### ISSUE TITLE
Crash when invite doesn't have timestamp

### ISSUE THREAD

**Issue by Quiark** [QMatrixClient/libqmatrixclient#76]
As reported earlier in the channel, sometimes I get room invites (usually from `ChanServ` or `NickServ` on the freenode IRC bridge) which trigger an ASSERT in `event.cpp :  53` when checking that timestamp is a double. 

Example: https://hastebin.com/wefekeputi.js

**Comment by KitsuneRal** [comment]
Should be fixed by https://github.com/QMatrixClient/libqmatrixclient/commit/c898caed6a7c8d7a5466d556b2d186ddc861884b
